name: manual trigger test
on:
  workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v4
      - name: Use Hello Name Action
        uses: akshayasgo/hello-name-action@main # Replace 'main' with your branch or tag
        with:
          name: "User from Other Repo"